#
# 2-1-race.asm
#
# An assembly file generated by 2-1-race.c
# PLEASE REFER TO THE LINE 35-37 FOR THE CRITICAL SECTION 
#
# @author: karu-rress
#

	.text
	.globl	counter           # The counter variable
	.bss
	.align 4
	.type	counter, @object
	.size	counter, 4        # The size of the counter variable
counter:
	.zero	4                 # Initialize the counter variable to 0
	.text
	.globl	add               # The add function 
	.type	add, @function
add:
.LFB0:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	movq	%rdi, -24(%rbp)
	movl	$0, -4(%rbp)
	jmp	.L2

.L3:
# # # # # # IMPORTANT: THE CRITICAL SECTION # # # # # #
	movl	counter(%rip), %eax    # 1. Read the value of counter (eax <= counter)
	addl	$1, %eax               # 2. Add 1 to the value        (eax += 1)
	movl	%eax, counter(%rip)    # 3. Write the new value back  (counter <= eax)
# # # # # # THE END OF THE CRITICAL SECTION # # # # # #
	addl	$1, -4(%rbp)           # this is just for the loop counter
.L2:
	cmpl	$999999, -4(%rbp)  
	jle	.L3
	movl	$0, %eax
	popq	%rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE0:
	.size	add, .-add
	.section	.rodata
.LC0:
	.string	"Counter: %d\n"
	.text
	.globl	main
	.type	main, @function


# The main function	
main:
.LFB1:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	subq	$48, %rsp
	movq	%fs:40, %rax
	movq	%rax, -8(%rbp)
	xorl	%eax, %eax
	movl	$0, -40(%rbp)
	jmp	.L6
.L7:
	leaq	-32(%rbp), %rax
	movl	-40(%rbp), %edx
	movslq	%edx, %rdx
	salq	$3, %rdx
	addq	%rdx, %rax
	movl	$0, %ecx
	leaq	add(%rip), %rdx
	movl	$0, %esi
	movq	%rax, %rdi
	call	pthread_create@PLT           # pthread_create
	addl	$1, -40(%rbp)
.L6:
	cmpl	$1, -40(%rbp)
	jle	.L7
	movl	$0, -36(%rbp)
	jmp	.L8
.L9:
	movl	-36(%rbp), %eax
	cltq
	movq	-32(%rbp,%rax,8), %rax
	movl	$0, %esi
	movq	%rax, %rdi
	call	pthread_join@PLT            # pthread_join
	addl	$1, -36(%rbp)
.L8:
	cmpl	$1, -36(%rbp)
	jle	.L9
	movl	counter(%rip), %eax
	movl	%eax, %esi
	leaq	.LC0(%rip), %rax
	movq	%rax, %rdi
	movl	$0, %eax
	call	printf@PLT
	movl	$0, %eax
	movq	-8(%rbp), %rdx
	subq	%fs:40, %rdx
	je	.L11
	call	__stack_chk_fail@PLT
.L11:
	leave
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE1:
	.size	main, .-main
	.ident	"GCC: (GNU) 14.2.1 20240910"
	.section	.note.GNU-stack,"",@progbits
